### ISSUE TITLE
Debbuging is not working

### ISSUE THREAD

**Issue by zoiverd** [luiscantero/angular2-webpack-dotnet-core#2]
Hi,

I download the code and run in IE, they recognize the map files but don't stop in breakpoint.

**Comment by luiscantero** [comment]
Hi, I guess you mean that it doesn't stop in Visual Studio?
Does VS show the breakpoint in red when you run it or does it show a yellow warning sign for the breakpoint saying that no source files where loaded?

**Comment by zoiverd** [comment]
On really VS don't recognize the symbols...

![image](https://cloud.githubusercontent.com/assets/16689641/19526600/a6b766f0-9603-11e6-9634-dc8651bf040d.png)

But even when I run in IE and try to debug in script files, they don't stop.
![image](https://cloud.githubusercontent.com/assets/16689641/19526667/e372b9b4-9603-11e6-9596-e6351cb76bdb.png)

PS: Sorry my poor english...

**Comment by luiscantero** [comment]
Did you run `npm run build:dev` to create the map filed?
Do you see the file app.js.map (> 250 kb) and the other map files under wwwroot?

**Comment by zoiverd** [comment]
Yes,

I follow all steps in readme

[image: Imagem inline 1]

atenciosamente,

Rafael Gonçalves de Oliveira

2016-10-19 15:19 GMT-02:00 luiscantero <notifications@github.com>:

**Comment by luiscantero** [comment]
I don't see your attachment. I need to know if the map files are there. Also, if they are there, open them with Notepad and you should see right at the top the absolute path to the source files. Can your confirm?

**Comment by zoiverd** [comment]
Yes the map is there

![image](https://cloud.githubusercontent.com/assets/16689641/19531075/109166be-9615-11e6-9dd5-57657ce5d511.png)

![image](https://cloud.githubusercontent.com/assets/16689641/19531114/3dfae5a8-9615-11e6-8e19-e47dc121a325.png)

**Comment by luiscantero** [comment]
You seem to be using another webpack config file. Can you try to clone the repo to another folder under C:\Temp, then run `npm install ` and `npm run build:dev` again?

The files in wwwroot should look like this by default:
![vs](https://cloud.githubusercontent.com/assets/1353540/19531971/0a1e76c6-963a-11e6-8121-fdbd891fcea8.PNG)

Also, the map files should contain absolute paths to your sources, like this:
![map](https://cloud.githubusercontent.com/assets/1353540/19532073/6f3828b8-963a-11e6-827d-c77ce850cfbf.PNG)

**Comment by luiscantero** [comment]
Can you pls confirm if it worked, so that I can close this?
Obrigado.

**Comment by zoiverd** [comment]
Sorry, i had no time to test yet...
will do this tests today and return...

Em 22 de out de 2016 1:00 PM, "luiscantero" <notifications@github.com>
escreveu:
