### ISSUE TITLE
Build issue "Cannot find name 'require'"

### ISSUE THREAD

**Issue by ssashok10** [luiscantero/angular2-webpack-dotnet-core#3]
I have downloaded the source code and installed all the packages using "npm install" command. When i tried to build the project, i am seeing the below error messages,

1. Build:Cannot find name 'require'
2. Build:Cannot find name 'process'

I haven't changed any of the project files once i downloaded it and i am using Visual Studio 2015 Enterprise edition with update 3. Is there anything that i am missing to build this project through visual studio directly?

**Comment by luiscantero** [comment]
You need to build like it says in the readme file, e.g. npm run build:dev
